# Numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆) `hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆) `hint: vector is a single raw array`

In [2]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. How to find the memory size of any array, creat a random 5x6 array and check the sizs (★☆☆)

In [11]:
import numpy as np
x=np.arange(1,31)
#print (x)
x.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

#### 4. How to get the documentation of the numpy add function from the command line? (★☆☆) `hint: use info or ?`

In [12]:
np.add(1.0, 4.0)  #print(np.info(np.add))

5.0

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆) `hint: array[x]`

In [15]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector (single raw array) with values ranging from 10 to 49 (★☆☆) `hint: arange`

In [16]:
x = np.linspace(10,49,12,endpoint=True)[1:-1]
print(x)

[13.54545455 17.09090909 20.63636364 24.18181818 27.72727273 31.27272727
 34.81818182 38.36363636 41.90909091 45.45454545]


#### 8. Show how you can Reverse a vector (first element becomes last) (★☆☆)`hint: use index of -1`

In [17]:
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) `hint: use range and reshape!`

In [24]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) `hint: use the np.nonzero`

In [36]:
arr = np.array([0, 8, 7, 0, 4, 0, 0])
#arr = np.array([[0, 8, 0], [7, 0, 0], [-5, 0, 1]])
  
#print ("Input  array : \n", arr)
    
out_tpl = np.nonzero(arr)
print ("Indices of non zero elements : ", out_tpl) 

Indices of non zero elements :  (array([1, 2, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) `hint: use index and use np.eye`
the following is an example of 5x4 identity matrix


```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

```



In [37]:
x=np.identity(3)
print('3x3 matrix:')
print(x)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) `hint: np.random.random`

In [38]:
x = np.random.random((3,3,3))
print(x)

[[[0.98747908 0.51175377 0.9105963 ]
  [0.58262386 0.84224652 0.76155925]
  [0.57573504 0.67624419 0.74915182]]

 [[0.41952116 0.95735401 0.44988863]
  [0.49314616 0.85141886 0.18694518]
  [0.23035964 0.41363387 0.24873825]]

 [[0.21655984 0.82604072 0.58638876]
  [0.36723551 0.37115757 0.44881656]
  [0.75088242 0.53071895 0.44927049]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) `hint: min, max`

In [40]:
 x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.84307596 0.67864297 0.71808576 0.6011748  0.94612808 0.93731523
  0.06349626 0.82520874 0.29592182 0.05030306]
 [0.92567824 0.28543699 0.14677745 0.66944302 0.14718728 0.82128467
  0.96114773 0.53272227 0.27613995 0.69643209]
 [0.52728917 0.41140583 0.60870501 0.48373345 0.96006683 0.19710316
  0.54642321 0.45600782 0.27287102 0.71650681]
 [0.70944176 0.06503834 0.24201261 0.48157369 0.88520366 0.48194676
  0.63609777 0.9013931  0.18757041 0.18812505]
 [0.77443117 0.56035991 0.20812574 0.31836779 0.59697572 0.24699886
  0.64701719 0.87286253 0.47744109 0.56274607]
 [0.75407174 0.71557113 0.62632583 0.86511095 0.81545964 0.57411774
  0.73804285 0.98709103 0.83387295 0.66742548]
 [0.10182783 0.4954743  0.53319912 0.67015303 0.41882841 0.52863684
  0.0047892  0.06309197 0.35992912 0.5852235 ]
 [0.34983783 0.07231662 0.8246399  0.57659957 0.06221102 0.49341852
  0.5616852  0.41732577 0.26678503 0.13160012]
 [0.10055576 0.38189681 0.77084311 0.54589735 0.18497419 0.40789

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) `hint: mean`

In [41]:
x = np.random.random(30)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.64755788 0.838281   0.56193006 0.55078083 0.99555787 0.67813135
 0.76696955 0.70328588 0.48413372 0.7114384  0.69733133 0.09150599
 0.20543459 0.31697745 0.33127068 0.00501457 0.64903066 0.93656483
 0.65374545 0.97075136 0.25947496 0.67083507 0.10592289 0.99622623
 0.64672445 0.50326504 0.55015126 0.84486601 0.41884558 0.17642934]
Maximum value replaced by -1:
[ 0.64755788  0.838281    0.56193006  0.55078083  0.99555787  0.67813135
  0.76696955  0.70328588  0.48413372  0.7114384   0.69733133  0.09150599
  0.20543459  0.31697745  0.33127068  0.00501457  0.64903066  0.93656483
  0.65374545  0.97075136  0.25947496  0.67083507  0.10592289 -1.
  0.64672445  0.50326504  0.55015126  0.84486601  0.41884558  0.17642934]


#### 15. Create a 2d array as following, with 1 on the border and 0 inside.. see generated array (★☆☆)



```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```



In [42]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★★☆) `hint: see generated array np.pad   `

In [43]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [52]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

 ####18  What is the result of the following expression? (★☆☆) `hint: indexing the nan using np.nan`



```
Z = np.ones((5,5))
Z[0,1]=np.nan
Z
```



In [53]:
Z = np.ones((5,5))
Z[0,1]=np.nan
Z

array([[ 1., nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 18. Now, use this expression to find the index of your nan


```
np.argwhere(x!=x)    Hint: x is your array
```





In [54]:
x = np.array([[1,2,3,4],
              [2,3,np.nan,5],
              [np.nan,5,2,3]])
np.argwhere(np.isnan(x))

array([[1, 2],
       [2, 0]])

20. Generate the following array 


```
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```



#### 19. Extract the following values `array([ 1,  6, 11, 16])`. ` Hint: use np.diagonal()`

In [55]:
matrix = np.array(
         [[-2,  5,  3,  2],
          [ 9, -6,  5,  1],
          [ 3,  2,  7,  3],
          [-1,  8, -4,  8]])

diags = [matrix[::-1,:].diagonal(i) for i in range(-3,4)]
diags.extend(matrix.diagonal(i) for i in range(3,-4,-1))
print [n.tolist() for n in diags]

SyntaxError: ignored

In [ ]:
Z

array([7.29e-44, 1.96e-44, 2.80e-45, 1.35e-43, 5.75e-44, 9.95e-44,
       9.25e-44, 7.85e-44, 6.31e-44, 5.61e-45], dtype=float32)

#### 20. Try to use `np.diag` to Create a 5x5 matrix with diagonal values 11,11,11,11 (★★☆) Hint: use np.diag with k=0 and [11,11,11,11]. -- diag([11,11,11,11],k=-0)

#### 21.  Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) `Hint: use k=-1 when calling np.diag`

In [57]:
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


####22. Create a 8x8 matrix and fill it with a given pattern (★☆☆) Hint: use np.zeros and do the replace 



```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [62]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,4),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


#### 23. Use the `np.tile` to generate the same pattern 

```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [ ]:
b = np.array([[1, 2], [3, 4]])
np.tile(b, 2)
array([[1, 2, 1, 2],
       [3, 4, 3, 4]])
np.tile(b, (2, 1))
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 24. Generate then Normalize a 5x5 random matrix (★☆☆)  `hint: Normalization_array = (x_arr -mean_value(x))/std_value(x)`

In [63]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.00687678 0.73391777 0.90754594 0.11446958 0.75662477]
 [0.62791494 0.34421159 0.75573743 0.26359703 0.59530449]
 [0.82605002 0.12216319 0.58950983 0.94515141 0.3199512 ]
 [0.35625024 0.19521496 0.3853447  0.56609696 0.55898608]
 [0.01685239 0.85423092 0.72620037 0.49367034 0.93660335]]
After normalization:
[[0.         0.77487014 0.95992061 0.11467091 0.79907094]
 [0.6618938  0.35952673 0.79812522 0.27360886 0.62713804]
 [0.8730634  0.12287064 0.62096217 1.         0.33367034]
 [0.37235736 0.2007282  0.40336583 0.59600906 0.58843039]
 [0.01063187 0.90309822 0.76664504 0.51881778 0.9908896 ]]


#### 25. generate any 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

where 

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
```
will return

```
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
```




In [ ]:
Z = np.arange(11)
# Your code here!. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 26. Consider an integer vector Z, comment any iligal expressions (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z <- Z   2 << Z >> 2

#### 27. Generate two randon 1D array, How to find common values between two arrays? (★☆☆) `Hint: use intersect1d(Arr1,Arr2)`

#### 28. How to ignore all numpy warnings (not recommended)? (★☆☆)

####29. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```